version: '3.8'
services:
  app:
    build: .
    container_name: vetor_node_app
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    command: >
      sh -c "
      echo 'Aguardando o banco de dados ficar pronto...';
      while ! nc -z db 5432; do
        sleep 1;
      done;
      echo 'Banco de dados pronto!';
      npx prisma generate
      npx prisma migrate deploy;
      npm run start:dev;
      "
    networks:
      - backend

  db:
    image: postgres
    container_name: vetor_db_prisma
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: vetor_db_prisma
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    networks:
      - backend

  test:
    build: .
    command: sh -c "npm run test:e2e && tail -f /dev/null"
    container_name: vetor_db_test
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}

    networks:
      - backend
networks:
  backend:
    driver: bridge
